### ISSUE TITLE
Unable to generate surface mesh 

### ISSUE THREAD

**Issue by agvarghe** [ansys/pyprimemesh#500]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

Hi Martin Walters, Ninad Kamat

 

While trying to generate mesh using lucid class api , i get the following issue .

`
Traceback (most recent call last):

  File "e:/NON_CONFIDENTIAL/examples/rear_wing/f1_car_rear_wing.py", line 85, in <module>

    mesher.surface_mesh_with_size_controls(size_control_names="*")

  File "e:\gitHub_PyPrimeMesh\pyprime\pyprimemesh\pyprime_git_venv\lib\site-packages\ansys\meshing\prime\lucid\mesh_util.py", line 598, in surface_mesh_with_size_controls

    self.__surface_mesh_on_active_sf(generate_quads=generate_quads, scope=scope)

  File "e:\gitHub_PyPrimeMesh\pyprime\pyprimemesh\pyprime_git_venv\lib\site-packages\ansys\meshing\prime\lucid\mesh_util.py", line 316, in __surface_mesh_on_active_sf

    advanced_surfer_setup=prime.AdvancedSurferSetup(),

TypeError: __call__() missing 1 required positional argument: 'value'
`

### 📝 Steps to reproduce

mesher = lucid.Mesh(model)
`mesher.surface_mesh_with_size_controls(size_control_names="*")```

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2023 R2

### 🐍 Which Python version are you using?

3.8

### 📦 Installed packages

```shell
ansys-meshing-prime (0.4.dev8)
```

**Comment by agvarghe** [comment]
This defect is fixed after recreating the environment variable
