### ISSUE TITLE
Client unable to connect with server

### ISSUE THREAD

**Issue by agvarghe** [ansys/pyprimemesh#576]
1### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

While working on the latest version of the client 0.5.0.dev3, I am unable to establish connection between client and server. I am observing the following error
`_e:\gitHub_PyPrimeMesh\pyprime\pyprimemesh\.venv\lib\site-packages\pyvista\plotting\plotting\__init__.py:23: PyVistaDeprecationWarning: The `pyvista.plotting.plotting` module has been deprecated. `Plotter` is now imported as: `from pyvista.plotting import Plotter`.
  warnings.warn(
Failed to connect to PRIME GRPC server
Traceback (most recent call last):
  File "E:\gitHub_PyPrimeMesh\pyprime\pyprimemesh\src\ansys\meshing\prime\internals\grpc_communicator.py", line 86, in __init__
    grpc.channel_ready_future(self._channel).result(timeout=timeout)
  File "e:\gitHub_PyPrimeMesh\pyprime\pyprimemesh\.venv\lib\site-packages\grpc\_utilities.py", line 151, in result   
    self._block(timeout)
  File "e:\gitHub_PyPrimeMesh\pyprime\pyprimemesh\.venv\lib\site-packages\grpc\_utilities.py", line 97, in _block    
    raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError_

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "e:\NON_CONFIDENTIAL\examples\rear_wing\f1_car_rear_wing_test.py", line 8, in <module>
    with prime.launch_prime(timeout=60 , n_procs=1) as client:
  File "E:\gitHub_PyPrimeMesh\pyprime\pyprimemesh\src\ansys\meshing\prime\internals\launcher.py", line 242, in launch_prime
    return Client(server_process=server, ip=ip, port=port, timeout=timeout)
  File "E:\gitHub_PyPrimeMesh\pyprime\pyprimemesh\src\ansys\meshing\prime\internals\client.py", line 66, in __init__ 
    self._comm = GRPCCommunicator(
  File "E:\gitHub_PyPrimeMesh\pyprime\pyprimemesh\src\ansys\meshing\prime\internals\grpc_communicator.py", line 88, in __init__
    raise ConnectionError(
ConnectionError: Failed to connect to Server in given timeout of 60 secs`

### 📝 Steps to reproduce

from ansys.meshing import prime
import os
from ansys.meshing.prime import lucid
from ansys.meshing.prime.graphics import Graphics
DISPLAY = False

with prime.launch_prime(timeout=60 , n_procs=1) as client:
    model=client.model

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2024R1

### 🐍 Which Python version are you using?

3.8

### 📦 Installed packages

```shell
ansys-meshing-prime     0.5.0.dev3 E:\gitHub_PyPrimeMesh\pyprime\pyprimemesh
```

**Comment by ninad-kamat** [comment]
@agvarghe We have been through some instability with several thirdparty upgrades going in this release. Hopefully, all should be good now that we have released the dev6 server internally. Github code has been updated to dev6 on the main branch. The client should be available on PyPI either today or in a couple of days. Will keep you posted.

**Comment by ninad-kamat** [comment]
@agvarghe I released client 0.5.0.dev6 to PyPI. Can you try this with the latest development installation and update if this issue is still seen?

**Comment by ninad-kamat** [comment]
@agvarghe Can I close this? I have not seen this issue in later dev releases. Could be a mismatch as we went through compiler upgrades.

**Comment by ninad-kamat** [comment]
Closing the issue as this was resolved in future dev updates
