### ISSUE TITLE
Bug located in Mixing Elbow tutorial for prime.examples.download_elbow_fmd() in 2024 R1

### ISSUE THREAD

**Issue by hgrotjan** [ansys/pyprimemesh#773]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

The function
`mixing_elbow = prime.examples.download_elbow_fmd()`
fails with an error
Traceback (most recent call last):
```
  File "D:\...\PyMesh_Elbow.py", line 65, in <module>
    mesh_util.read(file_name=mixing_elbow)
  File "C:\Users\...\.ansys_python_venvs\Py3119_PyAnsys241\Lib\site-packages\ansys\meshing\prime\lucid\mesh_util.py", line 92, in read
    prime.FileIO(self._model).import_cad(
  File "C:\Users\...\.ansys_python_venvs\Py3119_PyAnsys241\Lib\site-packages\ansys\meshing\prime\core\fileio.py", line 504, in import_cad
    import_result = super().import_cad(temp_file_name, params)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\.ansys_python_venvs\Py3119_PyAnsys241\Lib\site-packages\ansys\meshing\prime\autogen\fileio.py", line 650, in import_cad
    result = self._comm.serve(self._model, command_name, self._object_id, args=args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\.ansys_python_venvs\Py3119_PyAnsys241\Lib\site-packages\ansys\meshing\prime\internals\error_handling.py", line 535, in wrapper_error_code
    raise PrimeRuntimeError(
ansys.meshing.prime.internals.error_handling.PrimeRuntimeError: CAD import failed.
```
CAD Import and tutorial works well when instead using this call:
`mixing_elbow = prime.examples.download_elbow_pmdat()`

### 📝 Steps to reproduce

Download and run tutorial
`python PyMesh_Elbow.py`

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2024 R1

### 🐍 Which Python version are you using?

3.11

### 📦 Installed packages

```shell
annotated-types==0.6.0
ansys-additive-core==0.17.2
ansys-api-additive==1.4.1
ansys-api-dbu==0.2.5
ansys-api-dyna==0.3.6
ansys-api-edb==1.0.3
ansys-api-fluent==0.3.22
ansys-api-geometry==0.3.8
ansys-api-mapdl==0.5.1
ansys-api-mechanical==0.1.1
ansys-api-meshing-prime==0.1.2
ansys-api-platform-instancemanagement==1.1.0
ansys-api-pyensight==0.3.7
ansys-api-sherlock==0.1.22
ansys-api-systemcoupling==0.1.0
ansys-dpf-composites==0.4.0
ansys-dpf-core==0.10.1
ansys-dpf-post==0.6.0
ansys-dyna-core==0.4.13
ansys-dynamicreporting-core==0.5.1
ansys-edb-core==0.1.3
ansys-fluent-core==0.19.2
ansys-geometry-core==0.4.11
ansys-grantami-bomanalytics==2.0.0
ansys-grantami-bomanalytics-openapi==2.0.0
ansys-grantami-recordlists==1.1.0
ansys-grantami-serverapi-openapi==2.0.0
ansys-hps-client==0.7.1
ansys-mapdl-core==0.67.0
ansys-mapdl-reader==0.53.0
ansys-math-core==0.1.3
ansys-mechanical-core==0.10.8
ansys-mechanical-env==0.1.4
ansys-meshing-prime==0.5.1
ansys-motorcad-core==0.4.3
ansys-openapi-common==1.5.1
ansys-optislang-core==0.6.3
ansys-platform-instancemanagement==1.1.2
ansys-pyensight-core==0.7.8
ansys-pythonnet==3.1.0rc3
ansys-rocky-core==0.1.0
ansys-seascape==0.2.0
ansys-sherlock-core==0.4.0
ansys-simai-core==0.1.4
ansys-systemcoupling-core==0.4.1
ansys-tools-path==0.5.2
ansys-turbogrid-api==0.4.0
ansys-turbogrid-core==0.4.0
appdirs==1.4.4
asgiref==3.8.1
backoff==2.2.1
backports.tarfile==1.1.1
bcrypt==4.1.2
beartype==0.18.5
bleach==6.1.0
bokeh==3.4.1
build==1.2.1
cachetools==5.3.3
certifi==2024.2.2
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
clr-loader==0.2.6
colorama==0.4.6
contourpy==1.2.1
cryptography==42.0.5
cycler==0.12.1
decorator==5.1.1
defusedxml==0.7.1
Deprecated==1.2.14
dill==0.3.8
Django==5.0.4
docker==7.0.0
docutils==0.21.2
ecdsa==0.19.0
elementpath==4.4.0
fabric==3.2.2
filelock==3.14.0
fonttools==4.51.0
fpdf2==2.7.8
geomdl==5.3.1
google-api-core==2.19.0
google-api-python-client==2.127.0
google-auth==2.29.0
google-auth-httplib2==0.2.0
googleapis-common-protos==1.63.0
grpcio==1.63.0
grpcio-health-checking==1.48.2
grpcio-status==1.48.2
httplib2==0.22.0
idna==3.7
importlib_metadata==7.1.0
invoke==2.2.0
jaraco.classes==3.4.0
jaraco.context==5.3.0
jaraco.functools==4.0.1
Jinja2==3.1.3
keyring==25.2.0
kiwisolver==1.4.5
linkify-it-py==2.0.3
lxml==5.2.1
Markdown==3.6
markdown-it-py==3.0.0
MarkupSafe==2.1.5
marshmallow==3.21.2
marshmallow-oneofschema==3.1.1
matplotlib==3.8.4
mdit-py-plugins==0.4.0
mdurl==0.1.2
more-itertools==10.2.0
nh3==0.2.17
numpy==1.26.4
packaging==24.0
pandas==2.2.2
panel==1.4.2
param==2.1.0
paramiko==3.4.0
pillow==10.3.0
Pint==0.23
pkginfo==1.10.0
platformdirs==4.2.1
plotly==5.22.0
plumbum==1.8.3
pooch==1.8.1
proto-plus==1.23.0
protobuf==3.20.3
psutil==5.9.8
pyaedt==0.7.10
pyansys==2024.1.8
pyansys-tools-versioning==0.5.0
pyasn1==0.6.0
pyasn1_modules==0.4.0
pycparser==2.22
pydantic==2.7.1
pydantic_core==2.18.2
Pygments==2.17.2
pygranta==2024.1.0
pyiges==0.3.1
PyNaCl==1.5.0
pyparsing==3.1.2
pypiwin32==223
pypng==0.20220715.0
pyproject_hooks==1.1.0
Pyro5==5.15
pyspnego==0.10.2
python-dateutil==2.9.0.post0
python-jose==3.3.0
python-keycloak==2.0.0
pytwin==0.6.0
pytz==2024.1
pyvista==0.43.6
pyviz_comms==3.0.2
pywin32==306
pywin32-ctypes==0.2.2
PyYAML==6.0.1
readme_renderer==43.0
requests==2.31.0
requests-negotiate-sspi==0.5.2
requests-ntlm==1.2.0
requests-toolbelt==1.0.0
rfc3986==2.0.0
rich==13.7.1
rpyc==5.3.1
rsa==4.9
scipy==1.13.0
scooby==0.9.2
semver==3.0.2
serpent==1.41
six==1.16.0
sqlparse==0.5.0
sseclient-py==1.8.0
sspilib==0.1.0
tenacity==8.2.3
tomli==2.0.1
tornado==6.4
tqdm==4.66.2
twine==5.0.0
typing_extensions==4.11.0
tzdata==2024.1
uc-micro-py==1.0.3
uritemplate==4.1.1
urllib3==1.26.18
vtk==9.3.0
wakepy==0.7.2
webencodings==0.5.1
wrapt==1.16.0
xmlschema==2.5.1
xyzservices==2024.4.0
zipp==3.18.1
```

**Comment by hgrotjan** [comment]
tutorial now works again well

**Comment by hgrotjan** [comment]
resolved, example files successfully found by script
