### ISSUE TITLE
Bug located in export mesh as a .key file (DYNA format)

### ISSUE THREAD

**Issue by agvarghe** [ansys/pyprimemesh#867]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

The user is unable to export the mesh in the form of a dyna file

the error observed is 
Traceback (most recent call last):
  File "D:\CustomerProjects\Microsoft\Solder_reflow_consulting\PyPrime\mesh_script.py", line 137, in <module>
    file_write.export_lsdyna_keyword_file(
  File "C:\Users\jhe\.ansys_python_venvs\venv\lib\site-packages\ansys\meshing\prime\core\fileio.py", line 512, in export_lsdyna_keyword_file
    result = super().export_lsdyna_keyword_file(temp_file_name, params)
  File "C:\Users\jhe\.ansys_python_venvs\venv\lib\site-packages\ansys\meshing\prime\autogen\fileio.py", line 581, in export_lsdyna_keyword_file
    result = self._comm.serve(self._model, command_name, self._object_id, args=args)
  File "C:\Users\jhe\.ansys_python_venvs\venv\lib\site-packages\ansys\meshing\prime\internals\error_handling.py", line 552, in wrapper_error_code
    result = func(*args, **kwargs)
  File "C:\Users\jhe\.ansys_python_venvs\venv\lib\site-packages\ansys\meshing\prime\internals\error_handling.py", line 507, in wrapper_handle_errors
    func_result = func(*args, **kwargs)
  File "C:\Users\jhe\.ansys_python_venvs\venv\lib\site-packages\ansys\meshing\prime\internals\grpc_communicator.py", line 187, in serve
    message = get_response(response, '')
  File "C:\Users\jhe\.ansys_python_venvs\venv\lib\site-packages\ansys\meshing\prime\internals\grpc_communicator.py", line 67, in get_response
    return separator.join(response.data for response in get_response_messages(response_iterator))
  File "C:\Users\jhe\.ansys_python_venvs\venv\lib\site-packages\ansys\meshing\prime\internals\grpc_communicator.py", line 67, in <genexpr>
    return separator.join(response.data for response in get_response_messages(response_iterator))
  File "C:\Users\jhe\.ansys_python_venvs\venv\lib\site-packages\ansys\meshing\prime\internals\grpc_communicator.py", line 58, in get_response_messages
    for response in response_generator:
  File "C:\Users\jhe\.ansys_python_venvs\venv\lib\site-packages\grpc\_channel.py", line 542, in __next__
    return self._next()
  File "C:\Users\jhe\.ansys_python_venvs\venv\lib\site-packages\grpc\_channel.py", line 968, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Connection reset"
        debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-08-28T13:30:13.6434084+00:00", grpc_status:14, grpc_message:"Connection reset"}"
has context menu

### 📝 Steps to reproduce

Create a volume mesh and export key file. (Ensure LsDyna is not installed on the machine)

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2024R2

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
ansys-meshing-prime=0.6.2
```

**Comment by waltersma** [comment]
@agvarghe confirmed this suspected to be an installation issue and has not been reproducible.  Closing now.  Please reopen if the issue repeats. Thanks
